# 工作流名称
name: Go Cross-Platform Build and Release

# 触发工作流的事件
on:
  # push 事件：当推送到 master 分支或 v*.*.* 格式的标签时触发
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  # pull_request 事件：当有 PR 指向 master 分支时触发
  pull_request:
    branches:
      - 'master'

# 环境变量
env:
  GO_MAIN_PATH: '.'
  BINARY_NAME: '429RouterBeat'

jobs:
  # ==================================
  # 构建 Job: 负责编译所有平台的文件
  # ==================================
  build:
    name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin # macOS
            goarch: amd64
          - goos: darwin # macOS Apple Silicon
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Prepare file names
        id: prep
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            BASE_NAME="${{ env.BINARY_NAME }}"
          else
            BASE_NAME="${{ env.BINARY_NAME }}-$(date +'%Y-%m-%d')"
          fi
          
          OUTPUT_NAME="${BASE_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ ${{ matrix.goos }} == 'windows' ]; then
            OUTPUT_NAME+='.exe'
          fi
          
          echo "OUTPUT_NAME=${OUTPUT_NAME}" >> $GITHUB_ENV

      - name: Build
        run: |
          echo "Building binary as ${{ env.OUTPUT_NAME }}"
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -ldflags="-s -w" -o "${{ env.OUTPUT_NAME }}" ${{ env.GO_MAIN_PATH }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ${{ env.OUTPUT_NAME }}

  # ==================================
  # 发布 Job: 仅在打标签时运行
  # ==================================
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    # 关键：只有在创建 tag 时才运行此 job
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./binaries

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./binaries/*"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
