# 工作流名称
name: Go Cross-Platform Build and Release

# 触发工作流的事件
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

# 环境变量
env:
  GO_MAIN_PATH: '.'
  BINARY_NAME: '429RouterBeat'

jobs:
  # ==================================
  # 构建 Job: 负责编译所有平台的文件
  # ==================================
  build:
    name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin # macOS
            goarch: amd64
          - goos: darwin # macOS Apple Silicon
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          # 如果 tar 错误持续出现，请将下一行改为 cache: false
          cache: true

      - name: Prepare file names
        id: prep
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            BASE_NAME="${{ env.BINARY_NAME }}"
          else
            BASE_NAME="${{ env.BINARY_NAME }}-$(date +'%Y-%m-%d')"
          fi
          
          OUTPUT_NAME="${BASE_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ ${{ matrix.goos }} == 'windows' ]; then
            OUTPUT_NAME+='.exe'
          fi
          
          echo "OUTPUT_NAME=${OUTPUT_NAME}" >> $GITHUB_ENV

      - name: Build
        run: |
          echo "Building binary as ${{ env.OUTPUT_NAME }}"
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -ldflags="-s -w" -o "${{ env.OUTPUT_NAME }}" ${{ env.GO_MAIN_PATH }}

      # 修正: 为每个产物提供唯一的名字来避免冲突
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # 例如: artifact-linux-amd64
          name: artifact-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ env.OUTPUT_NAME }}

  # ==================================
  # 发布 Job: 仅在打标签时运行
  # ==================================
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      # 修正: 使用通配符下载所有以 artifact- 开头的产物
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          # 指定下载后文件存放的目录
          path: ./binaries
          # 匹配所有由 build job 上传的产物
          pattern: artifact-*
          merge-multiple: true # 将所有下载的产物合并到 path 指定的单个目录中

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          # 从下载好的 ./binaries 目录中上传所有文件
          artifacts: "./binaries/*"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
